---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "doplhin-1-config"
  namespace: "default"
  labels:
    app: "doplhin-1"
data:
  VNC_PASSWORD: "yourPW"
  XFB_SCREEN: "1280x800x24"
  XFB_SCREEN_DPI: "150"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "doplhin-1"
  namespace: "default"
  labels:
    app: "doplhin-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "doplhin-1"
  template:
    metadata:
      labels:
        app: "doplhin-1"
    spec:
      containers:
      - name: "doplhin-vnc"
        image: "p2lvoizin/docker-ubuntu-doplhin-vnc"
        securityContext:
          privileged: true
          capabilities:
            add:
              - CAP_SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["/usr/bin/gcsfuse", "-o", "nonempty", "gretrogamesbucket", "/Games"]
          preStop:
            exec:
              command: ["/bin/fusermount", "-u", "/Games"]
        ports:
        - containerPort: 5900
          name: "vnc"
        env:
        - name: "VNC_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "VNC_PASSWORD"
              name: "doplhin-1-config"
        - name: "XFB_SCREEN"
          valueFrom:
            configMapKeyRef:
              key: "XFB_SCREEN"
              name: "doplhin-1-config"
        - name: "XFB_SCREEN_DPI"
          valueFrom:
            configMapKeyRef:
              key: "XFB_SCREEN_DPI"
              name: "doplhin-1-config"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "doplhin-1-hpa"
  namespace: "default"
  labels:
    app: "doplhin-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "doplhin-1"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
